sudo: false
language: node_js
node_js:
  - '8'

branches:
  only:
  - dev
  - master

cache:
  directories:
  - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_8bb3cbc3d43e_key -iv $encrypted_8bb3cbc3d43e_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - npm update

install:
  - npm install

script:
  - npm run testci
